# Generated by Django 2.1.7 on 2019-02-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
